# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import os
from ultralytics import YOLO
import cv2
video_path = "/content/{video}.mp4"
video_path_out = '{}_out.mp4'.format(video_path)
cap = cv2.VideoCapture(video_path)
ret, frame = cap.read()
H, W, _ = frame.shape
out = cv2.VideoWriter(video_path_out, cv2.VideoWriter_fourcc(*'MP4V'), int(cap.get(cv2.CAP_PROP_FPS)), (W, H))
#select the best weight from training
model_path="/content/best.pt"
model = YOLO(model_path)
threshold = 0.1

# Define colors for each class
class_colors = {
    0: (0, 0, 255),    # Class 0 (example: blue)
    1: (0, 255, 0),    # Class 1 (example: green)
    2: (255, 0, 0)     # Class 2 (example: red)
    # Add more colors as needed for each class
}

while ret:
    results = model(frame)[0]

    for result in results.boxes.data.tolist():
        x1, y1, x2, y2, score, class_id = result

        if score > threshold:
            # Get color for the current class_id
            color = class_colors.get(int(class_id), (0, 0, 0))  # Default to black if class_id not found

            # Draw bounding box
            cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 4)

            # Draw class label
            cv2.putText(frame, results.names[int(class_id)].upper(), (int(x1), int(y1 - 10)),
                        cv2.FONT_HERSHEY_SIMPLEX, 1.3, color, 3, cv2.LINE_AA)

    out.write(frame)
    ret, frame = cap.read()

cap.release()
out.release()
cv2.destroyAllWindows()